env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  no-underscore-dangle: [ 2, { "allow": [ "__filename", "__dirname" ] } ]

